title: "Noah Roberts"
description: "Systems & Tools - Python/C/C++ - Linux - Game/Graphics"
url: "https://SohCahNoah.github.io"
baseurl: ""
theme: minima

timezone: America/Los_Angeles
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/

header_pages:
  - projects.md
  - about.md

minima:
  hide_site_feed_link: true
  social_links:
    github: SohCahNoah
    linkedin: TO BE IMPLEMENTED

plugins:
  - jekyll-feed
  - jekyll-sitemap

sass:
  style: compressed

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock